# syntax=docker/dockerfile:1

FROM nvcr.io/nvidia/nvhpc:24.9-devel-cuda12.6-ubuntu22.04
RUN apt-get update
RUN apt-get -y install clang docker zip linux-headers-generic perl wget curl
#RUN curl -o /root/cmake-3.30.5.tar.gz https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5.tar.gz
#RUN tar -xzvf /root/cmake-3.30.5.tar.gz
